import math

# force of gravity m/s^2
g = 9.81

# W the masses of the arms in kilo 
w1 = 1
w2 = 1

# l length of the arms in meters
l1 = 1
l2 = 1

# q angle of inclination in degrees
q1 = math.radians(0)
q2 = math.radians(-0) #angle is in the opposite direction to the first angle

# d1 distance in meters of the first arm (length)
d1 = l1 * math.cos(q1)

# Fr1 force generated by the weight of the robotic arm in Newtons
Fr1 = w1 * g

# M1 torque moment of the first arm N/m
M1 = Fr1 * (.5 * d1)

# d2 distance in meters of the second arm (length)
d2 = l2 * math.cos(q2)

# d3 distance in meters of the second robotic arm on the x-axis
d3 = d1 + (.5 * d2)

# Fr2 force generated by the weight of the robotic arm in Newtons
Fr2 = w2 * g

# M1 torque moment of the second arm N/m
M2 = Fr2 * d3

# M summation of Moments in the whole arm
M = M1 + M2

print( "M = " + str(M) + " N/m" )