import math

arrayk = [5,10,20]
for i in arrayk :
    # force of gravity m/s^2
    g = 9.81

    # w arm masses in kilos
    w1 = 1
    k = i

    # q Inclination angle in degrees
    q1 = math.radians(45)

    # l arm length in meters
    l = 1

    # d1 arm distance in meters (length)
    d = l * math.cos(q1)

    # Fr1 force generated by the weight of the robotic arm in Newtons
    Fr1 = w1 * g
    # M1 torque of the first arm that generates its own weight in N / m
    M1 = (.5 * d) * (Fr1)

    # Fr2 force generated by the weight of the load in Newtons
    Fr2 = k * g
    # M2 torque of the arm generating the load in N / m
    M2 = d * Fr2

    # M summation of Moment in the whole arm
    M = M1 + M2

    print( "M = " + str(M) + " N/m with " + str(i) + " kilos load" )
